full_name: name
name: firstName
surname: lastName
address: address
phone: phoneNumber
claim: catchPhrase
created_at: date
updated_at: date
url: url
text: text
description: text
email: email
title: sentence
small_image: imageUrl,50,50
medium_image: imageUrl,640,480
big_image: imageUrl,2400,960
